### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "Kipper Skipper with billing account",
    "email": "kipskipbilling@mail.com",
    "address": "yomamas house",
    "dateOfBirth": "1995-09-09",
    "registeredDate": "2024-11-28"
}

###